### ISSUE TITLE
Add analytics for CreatED Hack with Google

### ISSUE THREAD

**Issue by GaganSD** [CreatEDHack/createdhack.github.io#12]

**Comment by notexactlyawe** [comment]
This already exists for createdhack.github.io, I think my job would be just to share it with you. If you send me your email (privately) then I'll try to get you added to the account/transfer ownership.

This also exists for ears-edi.com so I can do that at the same time if you like.

**Comment by GaganSD** [comment]
Wassim was looking for the ears-edi.com's analytics as well. You can transfer it to the society's email so the next committee can keep using the same analytics for CreatED and ears-edi.com http://ears-edi.com/contact

**Comment by notexactlyawe** [comment]
Ok, looks like the society Gmail address already has access. Do you want to try logging into it then going to https://analytics.google.com/analytics/web/#/report-home/a92880122w137451028p141719734 to see if you can access it?

**Comment by GaganSD** [comment]
Wassim just added me as a 'user' in the Google Analytics page, now I can access see CreatED's analytics through the link you sent me. Thank you!

**Comment by notexactlyawe** [comment]
:tada: Closing this, let me know if I can help with anything else
