### ISSUE TITLE
Integrate MyMLH for the applicant portal

### ISSUE THREAD

**Issue by GaganSD** [CreatEDHack/createdhack.github.io#13]

**Comment by caitlin-mcdougall** [comment]
Required fields:

First name
Last name
Phone number
Email
School (mlh wants this to be a dropdown)

**Comment by caitlin-mcdougall** [comment]
Required Agreements:

Checkbox with the following:

"I have read and agree to the [MLH Code of Conduct](http://mlh.io/code-of-conduct)"

Checkbox with the following about our affiliation with MLH:

"I authorise you to share my application information for event administration, ranking, MLH administration, pre- and post-event informational e-mails, and occasional messages about hackathons in-line with the [MLH Privacy Policy](https://mlh.io/privacy). I further agree to the terms of both the [MLH Contest Terms and Conditions](https://github.com/MLH/mlh-policies/tree/master/prize-terms-and-conditions) and the [MLH Privacy Policy](https://mlh.io/privacy)

**Comment by GaganSD** [comment]
I've shared the password with you @caitlin-mcdougall  if possible, please add the above-listed requirements by today. Additionally, we need this information from everyone.
- Essay-type question. (200 words max.) Why do you want to come to CreatED Hack?
- Essay-type question. (200 words max.) What is your favourite project you've worked on?
- **Attach your resume here**
- ** Consent to share your resume with the sponsors** (Requirement to attend the hackathon)

**Comment by romanakash** [comment]
Just link to https://my.mlh.io/oauth/authorize?client_id=cef9c1e6ba6e0e53dca74d35208a5b5a1f8aa2b8b9805724ef6657d15ce5a5ec&redirect_uri=https%3A%2F%2Fcreated-signup.herokuapp.com&response_type=token

**Comment by GaganSD** [comment]
It doesn't link back and it needs a UI.

**Comment by romanakash** [comment]
But it already has a UI?

**Comment by GaganSD** [comment]
Well, yes but it needs a makeover. 

Use the theme of the thanks.html page as the background. Replace the "thanks" with the fields.

**Comment by GaganSD** [comment]
Also, the buttons are not interactive. All it needs is some CSS, but we can't let people sign up before working on those minute details first.

**Comment by romanakash** [comment]
I cannot work on it right now, here's the repo if you want to make any changes https://github.com/romanakash/hclient

**Comment by GaganSD** [comment]
Same here. Tagging: @caitlin-mcdougall @IreneeG would any of you be able to work on this ASAP?

**Comment by GaganSD** [comment]
The application portal has officially been added to the website. Thanks to everyone who worked on it.
