### ISSUE TITLE
Add all sponsors on the website

### ISSUE THREAD

**Issue by GaganSD** [CreatEDHack/createdhack.github.io#18]
Some of our sponsors want us to put their name up as they have already transferred the money. 
Roman - Please put a list of sponsors, their tiers and the logo they want, I'll add it by tonight.

**Comment by romanakash** [comment]
54e26a1

**Comment by romanakash** [comment]
Wait pushed directly to master, so I'm gonna revert that

**Comment by GaganSD** [comment]
Thanks for making it consistent however they're too huge. Scale them down to 75% of the size it is now.

**Comment by romanakash** [comment]
#20
