### ISSUE TITLE
Add front end design to all webpages

### ISSUE THREAD

**Issue by GaganSD** [CreatEDHack/createdhack.github.io#24]
Basically add another layer on top of the purple background. You can add the particle.js's bubble design. Choose the color code and design you think will match with the bubble. It doesn't have to be interactive with the mouse, but they should move.

**Comment by martinstarkov** [comment]
Do you want it on each page or just behind the CreatED title on the front page?

**Comment by martinstarkov** [comment]
@GaganSD

**Comment by GaganSD** [comment]
Each page, as it looks bland right now.
