### ISSUE TITLE
Make Bronze Category

### ISSUE THREAD

**Issue by GaganSD** [CreatEDHack/createdhack.github.io#26]
Put Mokanix, Lime Systems, Digital Ocean in Bronze as they only provided hardware. @romanakash  please confirm if this is right.  I can think Wolfram and Digital Ocean can stay in Silver as they provided us software worth £10,000

**Comment by martinstarkov** [comment]
"Put [...] Digital Ocean in Bronze"
---
"[...] Digital Ocean can stay in Silver"

I took what you said first and put it in Bronze. Let me know if you want it back in Silver.
