### ISSUE TITLE
Remove particle.js from front page

### ISSUE THREAD

**Issue by GaganSD** [CreatEDHack/createdhack.github.io#27]

**Comment by martinstarkov** [comment]
Why do you keep changing your mind? This is the third time you want me to remove/add the particles.

**Comment by martinstarkov** [comment]
You can do it from now on :)

**Comment by GaganSD** [comment]
I got feedback from some people and we concluded that particle.js doesn't look on the front page but looks ok on the other ones.
 
@martinstarkov I didn't assign this job to anyone

**Comment by GaganSD** [comment]
I Completed this
