### ISSUE TITLE
Add Student Experience Grant Logo and Acknowledgement line

### ISSUE THREAD

**Issue by caitlin-mcdougall** [CreatEDHack/createdhack.github.io#35]
The logo and the acknowledgement line can by found here:

https://www.ed.ac.uk/student-experience-grants/information-for-grant-recipients

This should be added to the Sponsors page (under supported by)

**Comment by martinstarkov** [comment]
The logo is unavailable. Please check the link

**Comment by martinstarkov** [comment]
https://www.ed.ac.uk/information-services/services/status-alerts
Wiki is down according to the status page.
What should I do meanwhile?

**Comment by martinstarkov** [comment]
Nvm previous comments (deleted). Wiki says the logo will be available at 1 pm. I will add this around that time.

**Comment by caitlin-mcdougall** [comment]
Thank you, I hadn't realised the wiki went down today sorry. Thanks for your patience 😄

**Comment by caitlin-mcdougall** [comment]
Thank you, I hadn't realised the wiki went down today sorry. Thanks for your patience 😄

**Comment by martinstarkov** [comment]
I will make the logo link to https://www.ed.ac.uk/student-experience-grants 
Let me know if you want this changed

**Comment by martinstarkov** [comment]
Also, if you think the acknowledgement line looks out of place, I could make it show up when you hover over the logo like this:
![image](https://user-images.githubusercontent.com/5933654/74828751-905b4b00-5307-11ea-935a-a0adc11e8c13.png)

**Comment by martinstarkov** [comment]
I will make the acknowledgment line show up as a tooltip when you hover over the logo.

**Comment by caitlin-mcdougall** [comment]
Displaying it on hover sounds like the nicest way of displaying it. Thank you!

**Comment by martinstarkov** [comment]
Please let me know that it works as you would expect.

**Comment by caitlin-mcdougall** [comment]
Looks perfect, the link is fine but maybe to this: https://www.ed.ac.uk/student-experience-grants/about instead? Since it directly talks about the grant and who is involved
