### ISSUE TITLE
Change background template

### ISSUE THREAD

**Issue by GaganSD** [CreatEDHack/createdhack.github.io#4]
@romanakash sent a template for the website we'll be using in teams. The misty wallpaper needs to be replaced with that.

**Comment by martinstarkov** [comment]
Fixed

**Comment by GaganSD** [comment]
The purple background needs to go all the way down till the end and should be interactive when you scroll it and thanks for getting the logo part done!

**Comment by martinstarkov** [comment]
Interactive in what way?

**Comment by GaganSD** [comment]
I've sent the details in discord

**Comment by GaganSD** [comment]
We decided to change the design and add the slanting white line instead
