### ISSUE TITLE
Add slanting design to the webpage

### ISSUE THREAD

**Issue by GaganSD** [CreatEDHack/createdhack.github.io#7]
https://kilianvalkhof.com/2017/design/sloped-edges-with-consistent-angle-in-css/

**Comment by martinstarkov** [comment]
Where specifically do you want these slanted lines? Please be more specific and add details about the placements and directions and angles; remember: I’m not a graphic designer

**Comment by GaganSD** [comment]
Ideally, we'd want to be consistent with the design we've chosen. So, it would be nice to have it a slanting transition instead of the current horizontal transition after every section. An example of this implementation is here: https://hackcambridge.com/

**Comment by GaganSD** [comment]
@martinstarkov Finished this
